### ISSUE TITLE
[Question]: Is there any plan to implement NTL library on SYCL tool? Asking because there was a hint in the NTL research paper in this direction?

### ISSUE THREAD

**Issue by BabarZKhan** [acsl-technion/ntl#3]

**Comment by haggaie** [comment]
Thanks for the question. We considered using sycl as a future direction, but haven't had a chance to explore it. I am not planning to do that in the near future.

**Comment by BabarZKhan** [comment]
Thanks for the reply. If I have more questions regarding your library, can I open issues here?

**Comment by haggaie** [comment]
Sure, I'd be happy to help if I can.
